-- =====================================================================
-- Migrate the prototype's 15 players into Supabase.
-- Idempotent — only runs if the players table is empty.
--
-- Six humans (panikova, gymskin, karavavov, donnyp, ricciardo, oldreliable)
-- carry an ea_user; their goals/apps/assists are overridden at read time
-- by EA Pro Clubs live data merged in via member_state.
-- The nine AI characters have no ea_user — their mock_* numbers are the
-- only source of truth for them.
-- =====================================================================
do $body$
begin
  if (select count(*) from public.players) = 0 then
    insert into public.players
      (id, name, short_name, number, ea_user, image,
       position, rating, rarity, nationality, stats,
       mock_goals, mock_apps, mock_assists, mock_clean_sheets,
       tags, accent_color, glow_color, archetype, lore, timeline,
       sort_order, visible)
    values

    -- HUMANS ─────────────────────────────────────────────────────
    ('panikova', 'Amir Panikova', 'PANIKOVA', 77, 'broddleeee1',
     '/uploads/pasted-1777415983890-0.png',
     'ST', 85, 'icon', 'RU',
     '{"PAC":85,"SHO":91,"PAS":72,"DRI":87,"DEF":22,"PHY":80}'::jsonb,
     187, 306, 43, null,
     array['The Calm (Formerly)','Aura Instability Risk','Vibe Injury Prone','Offside Non-Compliant'],
     '#ff2244', 'rgba(255,34,68,0.45)',
     'Chaos Icon',
     'Once heralded as the most composed striker in Pro Clubs history. Then something shifted. Nobody knows what. Not even him.',
     '[{"era":"The Rise","note":"187 goals. Cold. Clinical. Legendary."},{"era":"The Collapse","note":"Missed a penalty against 10 men. Blamed a seagull."},{"era":"The Rebirth","note":"Sad Boi era begins. Chaos becomes the method."}]'::jsonb,
     10, true),

    ('gymskin', 'Gymskin', 'GYMSKIN', 95, 'NoticeMeSenpepe',
     '/uploads/pasted-1777416552965-0.png',
     'CDM', 88, 'legend', '🌟',
     '{"PAC":80,"SHO":88,"PAS":85,"DRI":92,"DEF":45,"PHY":75}'::jsonb,
     278, 298, 127, null,
     array['Aura Commander','Coffee Calibrated','Drop the Shoulder™','Streamer-God Hybrid'],
     '#9b5de5', 'rgba(155,93,229,0.45)',
     'Aura Commander',
     'Operates on a frequency science cannot explain. Will not play before coffee reaches exactly 95 degrees. Non-negotiable.',
     '[{"era":"The Awakening","note":"Discovered \"Drop the Shoulder™\" aged 19. Patent pending."},{"era":"The Aura Era","note":"278 goals. Mostly from impossible angles."},{"era":"The Calibration","note":"Coffee ritual introduced. Win rate +34%."}]'::jsonb,
     20, true),

    ('karavavov', 'Dmitri Karavavov', 'KARAVAVOV', 11, 'AnGeRy SpUrD',
     '/uploads/Karavavov.png',
     'CAM', 87, 'rare', 'RU',
     '{"PAC":78,"SHO":74,"PAS":91,"DRI":88,"DEF":55,"PHY":70}'::jsonb,
     52, 241, 89, null,
     array['Creative Chaos Engine','Risk Merchant','Ball Retention: None'],
     '#f4a261', 'rgba(244,162,97,0.45)',
     'Trickster Genius',
     'The architect of beautiful sequences and catastrophic collapses. Often in the same passage of play. Frequently both.',
     '[{"era":"The Trickster","note":"Invented a skill move. Refused to name it."},{"era":"The Chaos Phase","note":"Lost the ball 847 times in one season. Still assisted 89."},{"era":"The Acceptance","note":"Manager stopped telling him to keep it simple."}]'::jsonb,
     30, true),

    ('donnyp', 'Donald Partridge', 'DONNY P', 9, 'der bom113',
     '/uploads/pasted-1777417166292-0.png',
     'CF', 85, 'rare', 'ENG',
     '{"PAC":83,"SHO":79,"PAS":68,"DRI":80,"DEF":20,"PHY":76}'::jsonb,
     94, 198, 31, null,
     array['Early Release Specialist','Top Bins (Rare)','Wind Resistant','Confidence MAX'],
     '#e9c46a', 'rgba(233,196,106,0.45)',
     'Unreliable Technician',
     'Confident. Emphatic. Wildly inconsistent. Has scored some absolute worldies. Has also missed from 3 yards. Claims wind resistance for both.',
     '[{"era":"The Promise","note":"Scored a bicycle kick on debut. Never mentioned since."},{"era":"The Sitter Era","note":"DONNY P MISSES SITTER, CLAIMS WIND RESISTANCE."},{"era":"The Redemption Arc","note":"Top bins from 35 yards. \"I meant it.\" He did not."}]'::jsonb,
     40, true),

    ('ricciardo', 'Daniel Ricciardo', 'RICCIARDO', 7, 'ItsJustAhsan',
     '/uploads/Ricciardo.png',
     'RW', 86, 'rare', 'AUS',
     '{"PAC":90,"SHO":72,"PAS":58,"DRI":85,"DEF":30,"PHY":78}'::jsonb,
     23, 187, 12, null,
     array['No Cross Completion','Performance Variance MAX','Chaos Merchant','RICCIARDO STILL HASN''T COMPLETED A CROSS'],
     '#00c8ff', 'rgba(0,200,255,0.45)',
     'Chaos Merchant',
     'Fast. Unpredictable. Has never successfully completed a cross in his career. Cross completion rate: 0.0%. We have checked. Many times.',
     '[{"era":"The Arrival","note":"Fastest player in the club. Great. What could go wrong."},{"era":"The Cross Incident","note":"Attempted 847 crosses. Zero completed. Ongoing investigation."},{"era":"The Acceptance","note":"Cross attempts now celebrated ironically. Still not completed one."}]'::jsonb,
     50, true),

    ('oldreliable', 'Old Reliable', 'OLD RELIABLE', 6, 'Shmuelly',
     '/uploads/old-reliable.png',
     'CM', 78, 'rare', '🌟',
     '{"PAC":70,"SHO":65,"PAS":80,"DRI":72,"DEF":70,"PHY":74}'::jsonb,
     0, 0, 0, null,
     array['Steady','Quietly Effective','Always Available'],
     '#06d6a0', 'rgba(6,214,160,0.4)',
     'The Glue',
     'Holds the team together. Doesn''t score, doesn''t need to. Always exactly where the ball is going to be — or already moving the play before the ball arrives.',
     '[{"era":"The Quiet Era","note":"Low-key brilliant. The teammates know."}]'::jsonb,
     60, true),

    -- AI CHARACTERS ──────────────────────────────────────────────
    ('jimenez', 'Jimenez', 'JIMENEZ', 1, null, null,
     'GK', 78, 'common', 'ES',
     '{"DIV":82,"HAN":76,"KIC":68,"REF":80,"SPD":60,"POS":85}'::jsonb,
     0, 134, 1, 29,
     array['Shot Stopper','Shouting Constantly','Blameless'],
     '#2a9d8f', 'rgba(42,157,143,0.4)',
     'The Keeper',
     'Concedes goals. Blames the defenders. Always. Without exception. The defenders have stopped arguing.',
     '[{"era":"The Debut","note":"29 clean sheets. Communicates entirely through pointing."},{"era":"The Philosophy","note":"\"If they don''t shoot they can''t score.\" Working on it."},{"era":"The Protocol","note":"Developed a 47-step distribution routine. Nobody is asking him to stop."}]'::jsonb,
     70, true),

    ('kamala', 'Kamala Harris', 'K. HARRIS', 2, null, null,
     'CB', 74, 'common', 'US',
     '{"PAC":70,"SHO":52,"PAS":74,"DRI":66,"DEF":79,"PHY":72}'::jsonb,
     3, 112, 8, null,
     array['Word Salad Distributor','Unexpectedly Composed','Coconut Tree Defender'],
     '#4361ee', 'rgba(67,97,238,0.4)',
     'The Defender',
     'Brings a unique verbal energy to defensive communication. Pre-match team talks are memorable if not always comprehensible.',
     '[{"era":"The Arrival","note":"First press conference lasted 40 minutes. Nobody is sure what was said."},{"era":"The Coconut Arc","note":"Delivered a pre-match speech about coconut trees. Kept a clean sheet."},{"era":"The Continuity","note":"Still here. Still talking. Defending is fine."}]'::jsonb,
     80, true),

    ('newsom', 'Gavin Newsom', 'NEWSOM', 3, null, null,
     'CB', 72, 'common', 'US',
     '{"PAC":68,"SHO":48,"PAS":71,"DRI":62,"DEF":77,"PHY":74}'::jsonb,
     2, 98, 5, null,
     array['Hair Immaculate','Press Conference Ready','Suspiciously Tanned'],
     '#457b9d', 'rgba(69,123,157,0.4)',
     'The Photogenic Defender',
     'Looks incredible at all times regardless of scoreline. Post-match interviews are polished. The defending is also polished. Somewhat.',
     '[{"era":"The Signing","note":"Arrived with a full media team. Hair perfect."},{"era":"The Performance","note":"Solid. Composed. Somehow always facing the camera."},{"era":"The Brand","note":"Has his own highlight reel. It is very well edited."}]'::jsonb,
     90, true),

    ('rosekirk', 'Rose Kirk', 'R. KIRK', 4, null, null,
     'RB', 75, 'common', 'ENG',
     '{"PAC":82,"SHO":60,"PAS":73,"DRI":76,"DEF":78,"PHY":71}'::jsonb,
     4, 121, 22, null,
     array['Relentless','Overlap Queen','Never Stops Running'],
     '#e63946', 'rgba(230,57,70,0.4)',
     'The Engine',
     'Runs. And runs. And runs. GPS data suggests she covers 14km per match. The sports scientists have asked her to slow down. She has not.',
     '[{"era":"The Debut","note":"Ran the full length of the pitch 11 times in 90 minutes."},{"era":"The Assist Era","note":"22 assists. None planned. All the result of running."},{"era":"The Legend","note":"Still running. Nobody has asked her to stop."}]'::jsonb,
     100, true),

    ('rubio', 'Marco Rubio', 'RUBIO', 5, null, null,
     'LB', 73, 'common', 'US',
     '{"PAC":75,"SHO":55,"PAS":69,"DRI":70,"DEF":76,"PHY":73}'::jsonb,
     1, 89, 11, null,
     array['Water Break Required','Sweating Profusely','Diplomatically Sound'],
     '#f4a261', 'rgba(244,162,97,0.4)',
     'The Diplomat',
     'Takes an unusually high number of water breaks. Performance improves markedly after hydration. The club has installed extra water stations.',
     '[{"era":"The Signing","note":"Arrived with 6 water bottles. Used all of them in the warm-up."},{"era":"The Water Era","note":"Three MOTM awards. All in games with unlimited hydration access."},{"era":"The Protocol","note":"New contract clause: minimum 4 water breaks per half."}]'::jsonb,
     110, true),

    ('noem', 'Kristi Noem', 'K. NOEM', 6, null, null,
     'CM', 70, 'common', 'US',
     '{"PAC":72,"SHO":66,"PAS":70,"DRI":68,"DEF":68,"PHY":76}'::jsonb,
     5, 77, 14, null,
     array['Unexpectedly Direct','No Nonsense','Controversial Decision Maker'],
     '#9b5de5', 'rgba(155,93,229,0.4)',
     'The Enforcer',
     'Takes decisive action on the pitch with minimal deliberation. Some decisions are inspired. Others require a review panel.',
     '[{"era":"The Debut","note":"Tackled the referee by accident. Yellow card. No apology."},{"era":"The Enforcer Era","note":"Became de facto captain of the defensive press."},{"era":"The Controversy","note":"Three red cards reviewed. One overturned. She was right that time."}]'::jsonb,
     120, true),

    ('rfk', 'Robert F Kennedy Jr', 'RFK JR', 14, null, null,
     'CM', 69, 'common', 'US',
     '{"PAC":68,"SHO":63,"PAS":72,"DRI":65,"DEF":64,"PHY":70}'::jsonb,
     6, 82, 17, null,
     array['Questionable Dietary Habits','Unconventional Methods','Bear Convinced He''s Fine'],
     '#e9c46a', 'rgba(233,196,106,0.4)',
     'The Wildcard',
     'Brings a unique perspective to team meetings. Pre-match nutrition choices are his own business. Performance is inconsistent but occasionally transcendent.',
     '[{"era":"The Signing","note":"Arrived carrying a smoothie of unspecified contents. Scored twice."},{"era":"The Methods","note":"Introduced an unorthodox training regime. Two players quit. Three improved."},{"era":"The Ongoing Situation","note":"The bear is fine. We have been asked not to elaborate."}]'::jsonb,
     130, true),

    ('hegseth', 'Pete Hegseth', 'HEGSETH', 8, null, null,
     'RW', 68, 'common', 'US',
     '{"PAC":76,"SHO":67,"PAS":55,"DRI":72,"DEF":42,"PHY":80}'::jsonb,
     8, 64, 6, null,
     array['Fox & Friends Correspondent','Extremely Confident','Chaotic Good'],
     '#e63946', 'rgba(230,57,70,0.4)',
     'The Pundit',
     'Plays with the energy of someone who has a lot of strong opinions and is not afraid to share them. Defending is not a priority.',
     '[{"era":"The Debut","note":"Scored on debut. Immediately gave a press conference about it."},{"era":"The Pundit Arc","note":"Began providing live commentary on his own performance mid-match."},{"era":"The Confidence","note":"Rating: 68. Self-assessed rating: 94. The gap is the content."}]'::jsonb,
     140, true),

    ('diakite', 'Steve Diakite', 'DIAKITE', 99, null, null,
     'ST', 80, 'rare', 'ENG',
     '{"PAC":84,"SHO":82,"PAS":65,"DRI":79,"DEF":25,"PHY":83}'::jsonb,
     41, 88, 12, null,
     array['EXILED','Awaiting Return','The Prodigal Striker','DO NOT CONTACT'],
     '#ff2244', 'rgba(255,34,68,0.4)',
     'The Exiled One',
     'Departed under circumstances that remain classified. The club has issued no statement. His shirt hangs in the changing room. Nobody has moved it.',
     '[{"era":"The Golden Era","note":"41 goals. Beloved. Everything was fine."},{"era":"The Incident","note":"[REDACTED BY CLUB LEGAL TEAM]"},{"era":"The Exile","note":"Location unknown. Number 99 retired. Then un-retired. Then retired again."}]'::jsonb,
     150, true);
  end if;
end $body$;
